### ISSUE TITLE
Using custom secret as Openstack credentials

### ISSUE THREAD

**Issue by behoof4mind** [syseleven/syseleven-exporter#84]
Hello,

We noticed that with current Helm Chart implementation it is not possible to customise Openstack Credentials.
The usage of the values:
```
openstack:
  projectId: ""
  username: ""
  password: ""
  # or
  application_credential_id: ""
  application_credential_secret: ""
```
is the must and it creates the secret.

In case if user would like not to store credentials as plain text in values file and use any other secrets management inside the cluster it is hard to override current logic.

---

If this is possible to implement separate secret usage (for example by parameter like `existingSecret` and option to not create default one from the Chart that will solve the problem.

Thank you in advance.
